services:
  app:
    build:
      context: .
      args:
        - VITE_PORT=${VITE_PORT:-8088}
        - PORT=${PORT:-8080}
    env_file:
      - .env
    ports:
      - "${VITE_PORT:-8088}:${VITE_PORT:-8088}"
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - VITE_API_BASE_URL=http://localhost:${PORT:-8080}/api
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/a11y_reports
    depends_on:
      - mongo
    volumes:
      - ./server/uploads:/app/server/uploads

  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: