version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:5173"
      - "3001:3001"
    environment:
      - VITE_API_BASE_URL=http://localhost:3001/api
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/a11y_reports
    depends_on:
      - mongo
    volumes:
      - ./server/uploads:/app/server/uploads

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: